parameters:
#    video.example.class: Infinitube\VideoBundle\Example

services:
#    video.example:
#        class: %video.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
